# Generated by Django 6.0.4 on 2026-04-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(max_length=20, unique=True)),
                ('processador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=20)),
                ('armazenamento_total_gb', models.PositiveIntegerField()),
                ('armazenamento_usado_gb', models.PositiveIntegerField(default=0)),
                ('bateria_pct', models.PositiveIntegerField(default=0)),
                ('status_conexao', models.CharField(choices=[('conectado_carregando', 'Conectado e carregando'), ('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('problema', 'Problema')], default='desconectado', max_length=25)),
                ('ultimo_log', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gestao.rack')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['serial_id'],
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='gestao.sala'),
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria_pct', models.PositiveIntegerField()),
                ('status_conexao', models.CharField(max_length=25)),
                ('armazenamento_usado_gb', models.PositiveIntegerField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gestao.device')),
            ],
            options={
                'verbose_name': 'Log de telemetria',
                'verbose_name_plural': 'Logs de telemetria',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
