# Generated by Django 6.0.4 on 2026-04-24 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_refactor_device_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetelemetry',
            name='bateria_pct',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='bateria_pct',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
